# Generated by Django 5.1.1 on 2024-09-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фотография')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('сategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webblog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
