# Generated by Django 5.1.1 on 2024-09-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='сategory',
            new_name='category',
        ),
    ]
