# Generated by Django 5.1.1 on 2024-09-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webblog', '0002_rename_сategory_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
